### ISSUE TITLE
Support unzipped folders

### ISSUE THREAD

**Issue by KoolenDasheppi** [joshie/beatsaber-to-audica#1]
I have a bunch of unzipped custom beat saber songs, and I don't feel like zipping em all up separately. You should implement support for unzipped songs. It'd be useful for existing installations.

**Comment by joshie** [comment]
Acknowledged. Will work on this for next release

**Comment by joshie** [comment]
This is fixed and reflected in the latest release.

https://github.com/joshie/beatsaber-to-audica/releases
https://github.com/joshie/beatsaber-to-audica/commit/8b66c3cc069b9617ec340ed83c3d35e860402b5f
