### ISSUE TITLE
Info.json undefined

### ISSUE THREAD

**Issue by Robbint** [joshie/beatsaber-to-audica#2]
I'm getting the following error when trying to convert Beat Saber songs:

```
var infoPath = filePath['info.json'].replace(/[^/]*$/,'');
                                     ^

TypeError: Cannot read property 'replace' of undefined
    at createAudica (D:\Temp\b2a\beatsaber_to_audica\app\bstoaud.js:72:40)
    at D:\Temp\b2a\beatsaber_to_audica\app\bstoaud.js:51:5
    at D:\Temp\b2a\beatsaber_to_audica\app\node_modules\recursive-readdir\index.js:88:20
    at FSReqWrap.oncomplete (fs.js:154:5)
```

I've tried with folders (songs) containing the info.json file, as well as songs from both bsaber and beatsaver. 

The songs does not get converted.

**Comment by joshie** [comment]
Hi @Robbint , this issue should be resolved with the latest build https://github.com/joshie/beatsaber-to-audica/releases/tag/0.2.1
